#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/chat_server.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/oscP5.jar" chat_server "$@"
